package com.andrewhicks.produce_erp.service;

import com.andrewhicks.produce_erp.exception.ResourceNotFoundException;
import com.andrewhicks.produce_erp.model.InventoryTransaction;
import com.andrewhicks.produce_erp.model.Lot;
import com.andrewhicks.produce_erp.model.Product;
import com.andrewhicks.produce_erp.repository.InventoryTransactionRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

/**
 * Business logic layer for InventoryTransaction management.
 *
 * InventoryTransactions are the immutable audit log of every stock movement in the system.
 * This service is the single point through which all stock changes must flow — every
 * receipt, sale, and adjustment calls record() here, which:
 *   1. Validates and resolves the product and lot references
 *   2. Sets a timestamp if not provided
 *   3. Calls LotService.adjustRemainingQuantity() to update the lot's available stock
 *   4. Persists the transaction record
 *
 * The service also provides read methods used by InventoryTransactionController to
 * query transaction history by product, lot, source document, or date range.
 *
 * Called by:
 *   PurchaseOrderService.receivePoLine() — posts RECEIPT transactions
 *   SalesOrderService.ship()            — posts SALE transactions (one per lot consumed)
 *   InventoryAdjustmentService.create() — posts ADJUSTMENT transactions
 *   InventoryTransactionController       — for direct manual transaction posting (advanced use)
 */
@Service
@RequiredArgsConstructor
@Transactional
public class InventoryTransactionService {

    private final InventoryTransactionRepository transactionRepository;
    private final ProductService productService;
    private final LotService lotService;

    /** Returns all transactions. Consider adding pagination for large datasets. */
    public List<InventoryTransaction> findAll() {
        return transactionRepository.findAll();
    }

    /** Finds a transaction by ID or throws ResourceNotFoundException. */
    public InventoryTransaction findById(Long id) {
        return transactionRepository.findById(id)
                .orElseThrow(() -> new ResourceNotFoundException("Transaction not found with id: " + id));
    }

    /**
     * Returns full transaction history for a product, newest-first.
     * Used for the stock ledger / movement history view per product.
     */
    public List<InventoryTransaction> findByProduct(Long productId) {
        return transactionRepository.findByProductProductIdOrderByTransactionDateDesc(productId);
    }

    /**
     * Returns full transaction history for a specific lot, newest-first.
     * Used for lot-level traceability (e.g. "what happened to batch LOT-001?").
     */
    public List<InventoryTransaction> findByLot(Long lotId) {
        return transactionRepository.findByLotLotIdOrderByTransactionDateDesc(lotId);
    }

    /**
     * Finds all transactions generated by a specific source document.
     * e.g. findByReference(PURCHASE_ORDER, 42) → all receipts from PO #42
     */
    public List<InventoryTransaction> findByReference(InventoryTransaction.ReferenceType refType, Long refId) {
        return transactionRepository.findByReferenceTypeAndReferenceId(refType, refId);
    }

    /**
     * Finds all transactions within a given time window.
     * Used for period-based reporting and stock reconciliation.
     */
    public List<InventoryTransaction> findByDateRange(LocalDateTime from, LocalDateTime to) {
        return transactionRepository.findByTransactionDateBetween(from, to);
    }

    /**
     * Records a new inventory transaction and applies its effect to the lot's stock level.
     *
     * This is the critical method that connects transaction recording to actual stock changes:
     *   1. Validates product and lot exist
     *   2. Defaults transactionDate to now if not set by caller
     *   3. Applies quantityChange to the lot via LotService (positive = add, negative = remove)
     *   4. Saves and returns the transaction record
     *
     * All three sources of transactions (receipt, sale, adjustment) call this method.
     * The calling service is responsible for setting transactionType, referenceType,
     * referenceId, quantityChange, and unitCost before calling record().
     */
    public InventoryTransaction record(InventoryTransaction transaction) {
        Product product = productService.findById(transaction.getProduct().getProductId());
        Lot lot = lotService.findById(transaction.getLot().getLotId());

        transaction.setProduct(product);
        transaction.setLot(lot);

        if (transaction.getTransactionDate() == null) {
            transaction.setTransactionDate(LocalDateTime.now());
        }

        // Apply the quantity change to the lot's remaining stock
        lotService.adjustRemainingQuantity(lot.getLotId(), transaction.getQuantityChange());

        return transactionRepository.save(transaction);
    }
}
